language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
services:
  - "mongodb"
sudo: false
before_install:
  - npm i mongoose@^4.0.0
script:
  - npm run lint
  - npm run compile
  - npm run test-ci
after_success:
  - npm install coveralls@~2.11.0
  - npm run report-coverage
branches:
  only:
    - master
